apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.9
        env:
        - name: RABBITMQ_USERNAME
          value: "rabbituser"
        - name: RABBITMQ_PASSWORD
          value: "aVery$ecureP4sswd"
        - name: RABBITMQ_SECURE_PASSWORD
          value: "yes"
        ports:
        - containerPort: 5672
          name: rabbitmq
        volumeMounts:
        - name: rabbitmq-storage
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-storage
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
